_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
aggregation:
    value: prob_mean
alpha:
    value: 0.75
architecture:
    value: densenet169
batch_size:
    value: 8
gamma:
    value: 2
loss_fn:
    value: Weighted BCE
lr:
    value: 0.0001
num_epochs:
    value: 20
scheduler:
    value: ReduceLROnPlateau
seed:
    value: 42
threshold:
    value: 0.5
